export const FAMILIES = [
  { id: 'modern', name: 'التقنية الحديثة', color: '#00F0FF' },
  { id: 'brutalism', name: 'الصرامة والبروتاليزم', color: '#FF6800' },
  { id: 'organic', name: 'العضوية والناعمة', color: '#00FF81' },
  { id: 'luxury', name: 'الأناقة والمينيماليزم', color: '#8B5CF6' },
  { id: '3d', name: 'العمق والـ 3D', color: '#FFA900' }
];

export const WINDOW_STYLES = [
  { id: 'standard-saas', name: 'القياسي', family: 'modern' },
  { id: 'teardrop', name: 'القطرة', family: 'modern' },
  { id: 'squircle', name: 'المربع الناعم', family: 'modern' },
  { id: 'edge-tab', name: 'شريط الحافة', family: 'modern' },
  { id: 'detached', name: 'المنفصل', family: 'modern' },
  { id: 'floating-screen', name: 'الشاشة العائمة', family: 'modern' },
  { id: 'neo-brutalist', name: 'بروتاليزم صلب', family: 'brutalism' },
  { id: 'terminal', name: 'شاشة الأوامر', family: 'brutalism' },
  { id: 'outline', name: 'البطاقة المفرغة', family: 'brutalism' },
  { id: 'ticket', name: 'التذكرة', family: 'brutalism' },
  { id: 'grid-block', name: 'البلوك الشبكي', family: 'brutalism' },
  { id: 'cloud', name: 'السحابة', family: 'organic' },
  { id: 'friendly-pill', name: 'الكبسولة الودودة', family: 'organic' },
  { id: 'egg', name: 'البيضة', family: 'organic' },
  { id: 'bouncy-bubble', name: 'الفقاعة الطائرة', family: 'organic' },
  { id: 'organic-attached', name: 'المتصل العضوي', family: 'organic' },
  { id: 'asymmetrical', name: 'الزوايا المتبادلة', family: 'organic' },
  { id: 'glassmorphism', name: 'الزجاج الفاخر', family: 'luxury' },
  { id: 'ultra-minimal', name: 'المينيماليست', family: 'luxury' },
  { id: 'faded-edge', name: 'التلاشي السلس', family: 'luxury' },
  { id: 'classic-elegant', name: 'الكلاسيكي الأنيق', family: 'luxury' },
  { id: 'detached-input', name: 'الإدخال العائم', family: 'luxury' },
  { id: '3d-pop', name: 'البعد الثالث', family: '3d' },
  { id: 'neumorphism', name: 'النيومورفيزم', family: '3d' },
  { id: 'layered-cards', name: 'الطبقات المتراكبة', family: '3d' },
  { id: 'deep-inner-shadow', name: 'الظل الداخلي', family: '3d' },
  { id: 'flip-card', name: 'القلب الثلاثي', family: '3d' }
];

export const BUBBLE_STYLES = [
  { id: 'modern', name: 'حديث', family: 'modern' },
  { id: 'classic', name: 'كلاسيكي', family: 'modern' },
  { id: 'squircle-bubble', name: 'مربع ناعم', family: 'modern' },
  { id: 'sharp', name: 'حادة', family: 'brutalism' },
  { id: 'brutalist-bubble', name: 'بروتالية', family: 'brutalism' },
  { id: 'terminal-bubble', name: 'طرفية', family: 'brutalism' },
  { id: 'beveled', name: 'مقطوعة', family: 'brutalism' },
  { id: 'grid-bubble', name: 'شبكية', family: 'brutalism' },
  { id: 'pill', name: 'كبسولة', family: 'organic' },
  { id: 'bouncy', name: 'قافزة', family: 'organic' },
  { id: 'circle-tail', name: 'دائرية بذيل', family: 'organic' },
  { id: 'pill-wide', name: 'كبسولة عريضة', family: 'organic' },
  { id: 'asym-bubble', name: 'غير متماثلة', family: 'organic' },
  { id: 'outline', name: 'مفرغة', family: 'brutalism' },
  { id: 'minimal-text', name: 'نص فقط', family: 'luxury' },
  { id: 'glassy-bubble', name: 'زجاجية', family: 'luxury' },
  { id: 'classic-elegant-bubble', name: 'أنيقة', family: 'luxury' },
  { id: '3d', name: 'ثلاثي الأبعاد', family: '3d' },
  { id: 'neumorphic', name: 'نيومورفيك', family: '3d' },
  { id: 'inset', name: 'محفورة', family: '3d' },
  { id: 'layered-card', name: 'بطاقة متراكبة', family: '3d' }
];

export const LAUNCHER_STYLES = [
  { id: 'round', name: 'دائرة', family: 'modern' },
  { id: 'square', name: 'مربع', family: 'modern' },
  { id: 'teardrop', name: 'قطرة', family: 'modern' },
  { id: 'oval', name: 'بيضاوي', family: 'modern' },
  { id: 'pill-text', name: 'كبسولة بنص', family: 'modern' },
  { id: 'bar', name: 'شريط', family: 'modern' },
  { id: 'half-circle', name: 'نصف دائرة', family: 'modern' },
  { id: 'diamond', name: 'ماسي', family: 'brutalism' },
  { id: 'hexagon', name: 'سداسي', family: 'brutalism' },
  { id: 'transparent', name: 'شفاف', family: 'luxury' },
  { id: 'ring', name: 'حلقة', family: 'luxury' },
  { id: 'icon-only', name: 'أيقونة فقط', family: 'luxury' },
  { id: 'glowing-dot', name: 'نقطة مشعة', family: 'luxury' },
  { id: 'cloud', name: 'سحابة', family: 'organic' },
  { id: 'tongue', name: 'لسان', family: 'organic' },
  { id: 'blob', name: 'فقاعة متحركة', family: 'organic' },
  { id: 'egg-shape', name: 'بيضة مقلوبة', family: 'organic' },
  { id: 'bubble-ring', name: 'حلقة واسعة', family: 'organic' },
  { id: 'glow', name: 'مشع', family: '3d' },
  { id: 'mechanical', name: 'ميكانيكي', family: '3d' },
  { id: 'stacked-circles', name: 'دوائر متراكبة', family: '3d' },
  { id: 'flip-launcher', name: 'سداسي دوار', family: '3d' }
];
